Repository uju-in/lime-backend, pull requests merged in 2024-01, with the labels that each got.

#1 [NO-JIRA] 취미 요구사항 변경
  lime-api/src/main/java/com/programmers/lime/domains/bucket/api/BucketController.java
  lime-api/src/main/java/com/programmers/lime/domains/bucket/api/dto/request/BucketCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/bucket/api/dto/request/BucketUpdateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/bucket/api/dto/response/BucketGetResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/feed/api/FeedController.java
  lime-api/src/main/java/com/programmers/lime/domains/hobby/HobbyController.java
  lime-api/src/main/java/com/programmers/lime/domains/hobby/api/dto/response/HobbyGetResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/hobby/api/dto/response/HobbyItem.java
  lime-api/src/main/java/com/programmers/lime/domains/hobby/application/HobbyService.java
  lime-api/src/main/java/com/programmers/lime/domains/inventory/api/InventoryController.java
  lime-api/src/main/java/com/programmers/lime/domains/inventory/api/dto/response/InventoryGetResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemEnrollRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/dto/request/VoteCreateRequest.java
  lime-domain/src/main/java/com/programmers/lime/common/model/Hobby.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/model/BucketProfile.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/model/FeedInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/inventory/model/InventoryInfoSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/inventory/model/InventoryProfile.java
Labels: enhancement

#3 [LIME-6] 네이버 클라우드 변경으로 인한 기존 설정 파일 변경
  lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberService.java
  lime-infrastructure/src/main/java/com/programmers/lime/s3/config/S3Configuration.java
Labels: enhancement

#4 [LIME-7] github action의 yml 파일 수정
  .github/workflows/CICD.yml
Labels: build

#8 [NO-JIRA] 닉네임 패턴에 한글 추가
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Nickname.java
Labels: enhancement

#9 [NO-JIRA] 요구사항에서 취미 선호도 삭제
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/Member.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Favorability.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Introduction.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/model/MemberProfile.java
Labels: enhancement

#7 [LIME-1] Kakao 소셜로그인 구현
  lime-api/build.gradle
  lime-api/src/main/java/com/programmers/lime/domains/auth/CustomOauth2User.java
  lime-api/src/main/java/com/programmers/lime/domains/auth/OAuth2UserService.java
  lime-api/src/main/java/com/programmers/lime/domains/auth/dto/OAuthAttributes.java
  lime-api/src/main/java/com/programmers/lime/domains/auth/vo/GoogleOAuth2UserInfo.java
  lime-api/src/main/java/com/programmers/lime/domains/auth/vo/KakaoOAuth2UserInfo.java
  lime-api/src/main/java/com/programmers/lime/domains/auth/vo/OAuth2UserInfo.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/MemberController.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberCheckEmailRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberLoginRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberSignupRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/response/MemberCheckEmailResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/response/MemberLoginResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberSecurityManager.java
  lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberService.java
  lime-api/src/main/java/com/programmers/lime/domains/member/application/dto/response/MemberLoginServiceResponse.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/MemberSecurity.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/auth/handler/OAuth2LoginFailureHandler.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/auth/handler/OAuth2LoginSuccessHandler.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/jwt/JwtService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/comment/repository/CommentRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/repository/FeedRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/Member.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/LoginInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Role.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/SocialInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/SocialType.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberChecker.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberModifier.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/repository/MemberRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberAppenderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberCheckerTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberModifierTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberReaderTest.java
  lime-infrastructure/src/main/java/com/programmers/lime/mail/EmailSender.java
  lime-infrastructure/src/main/java/com/programmers/lime/mail/config/MailConfiguration.java
Labels: enhancement

#11 [LIME-1] Oauth2UserService 위치 변경
  lime-api/src/main/java/com/programmers/lime/domains/auth/dto/OAuthAttributes.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/OAuth2UserService.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
Labels: bug

#12 [N O-JIRA] 변경된 요구사항에 맞게 프로필 정보 업데이트 기능 수정
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/Member.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Introduction.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberModifierTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberBuilder.java
Labels: enhancement

#10 [LIME-39] 멤버 아이템 폴더 생성, 삭제, 수정 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemDeleteRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemFolderCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemFolderUpdateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/ItemAddResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/MemberItemCreateResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemEnrollService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/MemberItemFolderService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/dto/MemberItemCreateServiceResponse.java
  lime-api/src/test/java/com/programmers/lime/domains/item/application/ItemServiceTest.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/domain/MemberItemFolder.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemEnrollValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderModifier.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/MemberItemAppenderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/MemberItemReaderTest.java
Labels: enhancement

#14 [LIME-39] 멤버 아이템 폴더 생성, 삭제, 수정 기능 추가를 main에 반영하기 위한 PR
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemDeleteRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemFolderCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemFolderUpdateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/ItemAddResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/MemberItemCreateResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemEnrollService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/MemberItemFolderService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/dto/MemberItemCreateServiceResponse.java
  lime-api/src/test/java/com/programmers/lime/domains/item/application/ItemServiceTest.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/domain/MemberItemFolder.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemEnrollValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderModifier.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/MemberItemAppenderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/MemberItemReaderTest.java
Labels: enhancement

#16 [NO-JIRA] 프로필 업데이트, 닉네임 중복확인 request dto 유효성 검증 추가
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberCheckNicknameRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/domain/vo/Nickname.java
Labels: bug

#17 [NO-JIRA] 닉네임 중복 시 예외 대신 bool 타입으로 반환하도록 변경
  lime-api/src/main/java/com/programmers/lime/domains/member/api/MemberController.java
  lime-api/src/main/java/com/programmers/lime/domains/member/application/MemberService.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberChecker.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberCheckerTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/member/implementation/MemberRemoverTest.java
Labels: enhancement, test

#18 [LIME - 1] 프로필 등록후 로그인 시 인코딩 된 주소로 redirect
  lime-api/src/main/java/com/programmers/lime/global/config/security/auth/handler/OAuth2LoginSuccessHandler.java
Labels: bug

#15 [LIME-9] 친구 관계 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/friendships/api/FriendshipController.java
  lime-api/src/main/java/com/programmers/lime/domains/friendships/api/dto/response/FriendshipGetByCursorResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/friendships/application/FriendshipService.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/domain/Friendship.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/implementation/FriendshipAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/implementation/FriendshipCounter.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/implementation/FriendshipReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/implementation/FriendshipRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/model/FriendshipSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/repository/FriendshipRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/repository/FriendshipRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/friendships/repository/FriendshipRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/implementation/MemberReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/model/MemberInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/member/model/MemberProfile.java
  lime-domain/src/test/java/com/programmers/lime/domains/friendships/implementation/FriendshipAppenderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/friendships/implementation/FriendshipCounterTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/friendships/implementation/FriendshipReaderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/friendships/implementation/FriendshipRemoverTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/friendship/domain/FriendshipBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/friendship/model/FriendshipSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberBuilder.java
Labels: enhancement, test

#19 [LIME-8] 나의 아이템 오브젝트 목록 조회 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemFolderCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/MemberItemObjectGetResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/MemberItemFolderService.java
  lime-domain/build.gradle
  lime-domain/src/main/java/com/programmers/lime/common/model/FavoriteType.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/domain/MemberItem.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/domain/MemberItemFolder.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/IFavoriteReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteInfoReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemFavoriteInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemFavoriteMetadata.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemFolderMetadata.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemMetadata.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepository.java
Labels: enhancement

#21 [LIME-50] 아이템 목록 조회 정렬 조건 추가
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemSortCondition.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
Labels: enhancement

#22 [LIME-52] 아이템 목록 조회에 취미 추가
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemEnrollRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
Labels: enhancement

#23 [LIME-54] 아이템 상세조회 기능추가
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/response/ItemGetResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/dto/ItemGetServiceResponse.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteInfoReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemMetadata.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewStatistics.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepository.java
Labels: enhancement

#24 [LIME-57] 아이템 목록 조회에 찜 개수, 리뷰 수 추가
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemCursorReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/FavoriteInfoForItemSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemCursorIdInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemInfoForItemSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/ItemSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/ReviewInfoForItemSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/ItemCursorReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/common/cursor/CursorIdBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/FavoriteInfoForItemSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemCursorIdInfoBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemCursorSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemInfoForItemSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ItemSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/item/model/ReviewInfoForItemSummaryBuilder.java
Labels: enhancement

#25 [LIME-58] 리뷰 이미지 추가
  lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/domain/ReviewImage.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewCursorReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/MemberInfoWithReviewId.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewCursorIdInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewCursorSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewImageRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/review/implementation/ReviewCursorReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberInfoBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberInfoWithReviewIdBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewCursorIdInfoBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewCursorSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewSummaryBuilder.java
  lime-infrastructure/src/main/java/com/programmers/lime/s3/S3Manager.java
Labels: enhancement

#27 [LIME-66] 리뷰 목록 조회 정렬 조건 추가
  lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewCursorReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewSortCondition.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/review/implementation/ReviewCursorReaderTest.java
Labels: enhancement

#28 [LIME-20] 포인트 지급 처리를 AOP -> Event로 변경
  lime-api/build.gradle
  lime-api/src/main/java/com/programmers/lime/domains/comment/application/CommentService.java
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-api/src/main/java/com/programmers/lime/global/event/point/PointEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/point/PointEventListener.java
  lime-api/src/main/java/com/programmers/lime/global/level/PayPoint.java
  lime-api/src/main/java/com/programmers/lime/global/level/PointManagerAop.java
Labels: refactor

#29 [LIME-61] bucket - bucketItem - item 양방향 연관관계 제거
  lime-api/src/main/java/com/programmers/lime/domains/bucket/application/BucketService.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/domain/Bucket.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/domain/BucketItem.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketModifier.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/repository/BucketItemRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/repository/BucketRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/repository/BucketRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/implementation/FeedAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepository.java
  lime-domain/src/test/java/com/programmers/lime/domains/bucket/implementation/BucketAppenderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/bucket/implementation/BucketModifierTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/bucket/implementation/BucketReaderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/feed/implementation/FeedAppenderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/feed/implementation/FeedReaderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/item/implementation/ItemCursorReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/bucket/domain/BucketBuilder.java
Labels: refactor
