Repository uju-in/lime-backend, pull requests merged in 2024-03, with the labels that each got.

#61 [NO-JIRA] fix vote keyword
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
  lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
Labels: bug, enhancement

#62 [NO-JIRA] 투표 랭킹에서 ttl 적용 안되는 문제 해결
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedisManager.java
Labels: bug

#64 [LIME-133] default 폴더를 가장 뒤에 오도록 기능 추가
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java
Labels: enhancement

#65 [LIME-134] 리뷰 내용 최소 글자 추가
  lime-api/src/main/java/com/programmers/lime/domains/review/api/dto/request/ReviewCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/review/api/dto/request/ReviewUpdateRequest.java
Labels: enhancement

#67 [LIME-122] 카카오 토큰요청 callback 경로 버그 수정
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
Labels: bug

#68 [LIME-122] requestMatchers 콜백 경로 추가
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
Labels: bug

#66 [LIME-131] 이벤트 비동기 처리를 통해 투표 로직과 레디스 로직 분리
  lime-api/src/main/java/com/programmers/lime/LimeApplication.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingAddEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingDecreasePopularityEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingDeleteEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingEventListener.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/vote/RankingUpdateEvent.java
  lime-api/src/test/java/com/programmers/lime/domains/vote/application/VoteServiceTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/MemberBuilder.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedisManager.java
Labels: enhancement

#69 [LIME-136] 피드 랭킹 업데이트 이벤트로 비동기 처리 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/feed/application/FeedService.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/feed/FeedRankingUpdateEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/ranking/feed/FeedRankingUpdateEventListener.java
Labels: enhancement

#72 [LIME-145] ci/cd 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: build

#70 [LIME-141] 채팅방 목록 조회, 채팅방 참여, 채팅방 인원수 조회, 채팅방 나가기 기능 구현
  lime-api/src/main/java/com/programmers/lime/domains/chatroom/api/ChatRoomController.java
  lime-api/src/main/java/com/programmers/lime/domains/chatroom/api/dto/response/ChatRoomGetListResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/chatroom/application/ChatRoomService.java
  lime-api/src/main/java/com/programmers/lime/domains/chatroom/application/dto/response/ChatRoomGetServiceListResponse.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/domain/ChatRoom.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/domain/ChatRoomMember.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomMemberAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomMemberReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomMemberRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/implementation/ChatRoomReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/model/ChatRoomInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/model/ChatRoomStatus.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/model/ChatRoomType.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomMemberRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomQueryDsl.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomQueryDslImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/chatroom/repository/ChatRoomRepository.java
Labels: enhancement

#73 [LIME-145] Blue/Green 배포 전략 변경
  .github/workflows/CICD.yml
Labels: build

#76 [LIME-142] demo 사이트에서 iframe 사용하기 위해 일시적인 security 변경
  lime-api/src/main/java/com/programmers/lime/global/config/chat/StompWebSocketConfig.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
Labels: bug
