Repository uju-in/lime-backend, pull requests merged in 2024-04, with the labels that each got.

#75 [LIME-71 ] 투표 참여 API 데드락 & 동시성 이슈 해결
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteLockManager.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-api/src/test/java/com/programmers/lime/domains/vote/application/VoteServiceTest.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/domain/Vote.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/domain/Voter.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoteCounter.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoteManager.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoteReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoteRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoterReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoterRepository.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteCounterTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteManagerTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteReaderTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteRemoverTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoterReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/domain/VoterBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/domain/setup/VoterSetUp.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/model/VoteCursorSummaryBuilder.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedisManager.java
Labels: bug, test

#79 [NO-JIRA] 투표 목록 조회 버그 수정
  lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
Labels: bug

#80 [LIME-157] 찜 관련 버그 수정
  lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FolderService.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderRemover.java
Labels: bug

#81 [LIME-156] 로그인 하지 않아도 리뷰 좋아요 할 수 있는 버그 수정
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeValidator.java
Labels: bug

#74 [NO-JIRA] ReadMe 업데이트
  README.md
Labels: documentation

#84 [LIME-144] 마이 투표 요구사항 변경
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
  lime-api/src/test/java/com/programmers/lime/domains/vote/application/VoteServiceTest.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteStatusCondition.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/member/domain/setup/MemberSetUp.java
Labels: enhancement, test

#77 [LIME-149] 채팅 기능 개선
  lime-api/src/main/java/com/programmers/lime/domains/chat/api/ChatController.java
  lime-api/src/main/java/com/programmers/lime/domains/chat/api/dto/response/ChatGetByCursorResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/chat/application/ChatService.java
  lime-api/src/main/java/com/programmers/lime/domains/chat/application/dto/response/ChatGetCursorServiceResponse.java
  lime-api/src/main/java/com/programmers/lime/global/cache/CacheType.java
  lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatAppendCacheEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatAppendEventListener.java
  lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatInitCacheEvent.java
  lime-api/src/main/java/com/programmers/lime/global/initializer/ChatCursorCacheInitializer.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/implementation/ChatReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/model/ChatSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/repository/ChatQueryDsl.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/repository/ChatQueryDslImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/repository/ChatRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/repository/ChatRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/chat/repository/ChatRepositoryForCursorImpl.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatCursorCacheAppender.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatCursorCacheManager.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatCursorCacheReader.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatCursorCacheUtil.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatLLScriptManager.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/CacheKeyAndStartIdxPair.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatCursorCache.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatCursorCacheResult.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatCursorCacheStatus.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/LLReadScript.java
  lime-infrastructure/src/main/resources/ReadByLinkedList.lua
Labels: enhancement

#78 [LIME-159] 레디스 메시지 브로커 설정
  lime-api/src/main/java/com/programmers/lime/domains/chat/application/ChatService.java
  lime-api/src/main/java/com/programmers/lime/global/config/chat/message/ChatMessageBrokerConfig.java
  lime-api/src/main/java/com/programmers/lime/global/config/chat/message/SimpleChatListener.java
  lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatSendMessageEvent.java
  lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatSendMessageEventListener.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatRedisMessageBrokerConfig.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/listener/ChatMessageListenerImpl.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/listener/IChatListener.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatInfoWithMemberCache.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/publisher/IChatPublisher.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/publisher/RedisChatPublisher.java
Labels: enhancement

#87 [NO-JIRA] 채팅 버그 수정
  lime-api/src/main/java/com/programmers/lime/domains/chat/application/ChatService.java
  lime-api/src/main/java/com/programmers/lime/domains/chatroom/application/ChatRoomService.java
  lime-api/src/main/java/com/programmers/lime/global/config/chat/message/ChatRoomRemoveSessionListener.java
  lime-api/src/main/java/com/programmers/lime/global/config/chat/message/SimpleChatListener.java
  lime-api/src/main/java/com/programmers/lime/global/event/chat/ChatSendMessageEventListener.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/ChatRedisMessageBrokerConfig.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/listener/ChatRoomRemoveAllSessionListenerImpl.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/listener/IChatRoomRemoveSessionListener.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/model/ChatRoomRemoveAllSessionInfo.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/publisher/ChatRoomRemoveSessionPublisher.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/chat/publisher/IChatRoomRemoveSessionPublisher.java
Labels: bug

#88 [LIME-165] 아이템 정렬 버그 수정
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
Labels: bug

#89 [LIME-165] Refresh Token 저장소 레디스로 변경
  lime-api/src/main/java/com/programmers/lime/domains/auth/application/OAuthUserService.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityManager.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/token/RefreshTokenManager.java
Labels: bug, enhancement

#90 [LIME-19] 피드 생성 기능 수정
  lime-api/src/main/java/com/programmers/lime/domains/feed/api/request/FeedCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/feed/application/FeedService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/domain/Feed.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/implementation/FeedAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/model/FeedCreateServiceRequest.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/model/FeedInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/feed/repository/FeedRepositoryForCursorImpl.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/feed/FeedBuilder.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/feed/model/FeedRankingInfo.java
Labels: refactor

#92 [NO-JIRA] sercurity swagger returntype 리팩토링
  lime-api/src/main/java/com/programmers/lime/domains/chat/api/ChatController.java
  lime-api/src/main/java/com/programmers/lime/domains/chatroom/api/ChatRoomController.java
  lime-api/src/main/java/com/programmers/lime/domains/favorite/api/FavoriteItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/ItemSearchRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemEnrollService.java
  lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
  lime-api/src/main/java/com/programmers/lime/global/cursor/CursorRequest.java
  lime-api/src/main/java/com/programmers/lime/global/error/GlobalExceptionHandler.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
Labels: documentation, enhancement, refactor
