Repository uju-in/lime-backend, pull requests merged in 2024-02, with the labels that each got.

#32 [LIME-74] 찜 목록 삭제 기능 리팩토링
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/FavoriteItemDeleteRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemDeleteRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/MemberItemFolderService.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepository.java
Labels: enhancement

#34 [LIME-51] 리뷰 관련 버그 수정 및 제약사항 추가
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewValidator.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepository.java
Labels: bug, enhancement

#35 [LIME-79] 리뷰 목록 조회에 로그인한 사용자 관련 기능 추가
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/ItemRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemRepositoryForCursorImpl.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewCursorReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewCursorSummary.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursor.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/review/implementation/ReviewCursorReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewCursorSummaryBuilder.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/review/ReviewInfoBuilder.java
Labels: enhancement

#36 [NO-JIRA] 로그인한 사용자 정보를 담는 모델 클래스 추가
  lime-domain/src/main/java/com/programmers/lime/domains/review/model/ReviewLoginMemberStatus.java
Labels: enhancement

#33 [LIME-76] 투표 생성 시 투표 인원 수 제한에 대한 요구사항 변경
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/dto/request/VoteCreateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/dto/request/VoteCreateServiceRequest.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/ItemReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/domain/Vote.java
Labels: enhancement

#39 [LIME-86] 리뷰 좋아요를 저장할 때 멤버 아이디가 저장 되도록 버그 수정
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewLikeService.java
Labels: bug

#40 [NO-JIRA] 그라파나 설정 추가
  lime-api/build.gradle
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
Labels: enhancement

#38 [LIME-85] 리뷰 이미지 수정 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/review/api/ReviewController.java
  lime-api/src/main/java/com/programmers/lime/domains/review/api/dto/request/ReviewUpdateRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewValidator.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewImageRepository.java
  lime-infrastructure/src/main/java/com/programmers/lime/s3/S3Manager.java
Labels: bug, enhancement

#41 [LIME-93]리뷰 이미지와 리뷰 좋아요가 있는 경우 삭제 안되는 버그 수정
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewImageRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewImageRepository.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/repository/ReviewLikeRepository.java
Labels: bug

#31 [NO-JIRA] SSE 리팩토링
  lime-api/src/main/java/com/programmers/lime/LimeApplication.java
  lime-api/src/main/java/com/programmers/lime/domains/comment/application/CommentService.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/AlarmCommentSubject.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/AlarmManager.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/AlarmManagerImpl.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/AlarmSubject.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/SseEmitters.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/SseEventListener.java
  lime-api/src/main/java/com/programmers/lime/domains/sse/SseService.java
  lime-api/src/main/java/com/programmers/lime/global/config/security/SecurityConfiguration.java
  lime-api/src/test/java/com/programmers/lime/domains/sse/SseEmittersTest.java
Labels: refactor

#43 [LIME-94] Loki 서버 전송을 위한 로그백 설정
  lime-infrastructure/build.gradle
  lime-infrastructure/src/main/resources/logback-spring.xml
Labels: enhancement

#44 [LIME-95] 찜 폴더 이동 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/item/api/ItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/item/api/dto/request/MemberItemMoveRequest.java
  lime-api/src/main/java/com/programmers/lime/domains/item/application/ItemService.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/domain/MemberItem.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemAppender.java
Labels: enhancement

#42 [LIME-87] 투표 변경된 요구사항 적용 1 - 투표 상세, 투표 랭킹 관련
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/dto/response/VoteRankResponse.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoteManager.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/implementation/VoterReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteDetailInfo.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoterRepository.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteManagerTest.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoterReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/domain/VoteBuilder.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRankingInfo.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedis.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRedisManager.java
Labels: bug, enhancement

#45 [LIME-96] 폴더에 포함되어 있는 아이템 개수 반환 기능 추가
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/model/MemberItemFolderMetadata.java
Labels: enhancement

#48 [NO-JIRA] 투표 상세 조회 결과에 취미 추가
  lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteDetailInfo.java
Labels: enhancement

#49 [LIME-91] 투표 목록 조회 요구사항 변경 - 투표 상태 조건, 정렬 조건 수정
  lime-api/src/main/java/com/programmers/lime/domains/vote/api/VoteController.java
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteSortCondition.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/model/VoteStatusCondition.java
  lime-domain/src/main/java/com/programmers/lime/domains/vote/repository/VoteRepositoryForCursorImpl.java
  lime-domain/src/test/java/com/programmers/lime/domains/vote/implementation/VoteReaderTest.java
  lime-domain/src/testFixtures/java/com/programmers/lime/domains/vote/model/VoteCreateImplRequestBuilder.java
Labels: enhancement

#52 [LIME-107] 찜 목록 조회 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/favorite/api/FavoriteItemController.java
  lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FavoriteItemService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/common/model/FavoriteType.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/IFavoriteReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteInfoReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFavoriteReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderFavoriteInfoReader.java
Labels: enhancement

#51 [NO-JIRA] 의존성 위치 변경
  lime-api/build.gradle
  lime-infrastructure/build.gradle
Labels: enhancement

#54 [LIME-111] 리뷰 관련 버그 수정
  lime-api/src/main/java/com/programmers/lime/domains/review/application/ReviewService.java
  lime-domain/src/main/java/com/programmers/lime/domains/review/implementation/ReviewLikeRemover.java
Labels: bug

#55 [NO-JIRA] 투표 랭킹 순위가 같을 경우, 투표 마감 시각이 빠른 순으로 정렬되도록 수정
  lime-api/src/main/java/com/programmers/lime/domains/vote/application/VoteService.java
  lime-infrastructure/src/main/java/com/programmers/lime/redis/vote/VoteRankingInfo.java
Labels: enhancement

#53 [LIME-108] 찜 아이템 이동 기능 추가
  lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FavoriteItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FolderService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepository.java
Labels: enhancement

#57 [LIME-107] LIME-107-BE-favorite-feat 브랜치 main 반영 PR
  lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FavoriteItemService.java
  lime-api/src/main/java/com/programmers/lime/domains/favorite/application/FolderService.java
  lime-common/src/main/java/com/programmers/lime/error/ErrorCode.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderValidator.java
  lime-domain/src/main/java/com/programmers/lime/domains/item/repository/MemberItemFolderRepository.java
Labels: enhancement

#50 [LIME-103] Bucket bulk-insert 리팩토링
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/domain/Bucket.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/domain/BucketItem.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketAppender.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/implementation/BucketRemover.java
  lime-domain/src/main/java/com/programmers/lime/domains/bucket/repository/BucketItemRepository.java
  lime-domain/src/test/java/com/programmers/lime/domains/bucket/implementation/BucketAppenderTest.java
Labels: refactor

#58 [LIME-107] transactional이 readonly로 인해 폴더가 생성되지 않는 버그 수정
  lime-domain/src/main/java/com/programmers/lime/domains/item/implementation/MemberItemFolderReader.java
Labels: bug

#59 [NO-JIRA] 레디스 보안 설정 추가
  lime-infrastructure/src/main/java/com/programmers/lime/redis/config/RedisConfig.java
Labels: enhancement
